stages:
  - build

  build:
    stage: build
    when: on_success
    only:
      - master
    image: docker:stable
    service:
      - docker:dind
    script:
      - docker login registry.gitlab.com
      - docker build -t registry.gitlab.com/jasmineerina15/blog-web-project .
      - docker push registry.gitlab.com/jasmineerina15/blog-web-project