stages:
  - build

  build:
    stage: build
    when: on_success
    only:
      - main
    image: docker:latest
    service:
      - docker:20:dind
    variables:
      DOCKER_HOST: tcp://localhost:8080
    script:
      - docker login registry.gitlab.com
      - docker build -t registry.gitlab.com/jasmineerina15/blog-web-project .
      - docker push registry.gitlab.com/jasmineerina15/blog-web-project